### ISSUE TITLE
Improve Home page loading performance

### ISSUE THREAD

**Issue by BurakKocak99** [SWE574-G3/Living-Stories-App#124]
The stories in the home page are loading slower than expected. The performance of the loading should be improved.

**Comment by yavuzsa** [comment]
Things to try: 
1- Try not to send unused information about stories to homepage
2- Try to host pictures in a seperate platform. Not as a column in the database.

**Comment by BurakKocak99** [comment]
This is imporoved by using StoryDTO by sending reduced data size to Front End.
