### ISSUE TITLE
Improve Recommendation engine performance

### ISSUE THREAD

**Issue by BurakKocak99** [SWE574-G3/Living-Stories-App#125]
The performance of the recommendation engine should be improved for usability purposes.

**Comment by JohnsL-U** [comment]
I realized that our live server has very limited number of user interactions, users, stories. As a result, it is difficult to gauge the limitations of recommendation engines performance. I suggest deleting meaningless users, increasing the user interactions significantly for the remaining users and then evaluating the recommendation engine's performance again.
