### ISSUE TITLE
Profile images uploaded by user should be reduced in size

### ISSUE THREAD

**Issue by yavuzsa** [SWE574-G3/Living-Stories-App#140]
When a user uploads a profile picture it should be resized to **256** at max in any dimesion

_e.g. 256x155 , 256x256 , 56x256_

_Optional:_
Also, instead of saving profile pictures as .png, using .jpg/.jpeg with a mediocre (70%-80% quality level) compression ratio would be more suitable for our application. We dont benefit from using lossless formats for profile pictures.

**Comment by yavuzsa** [comment]
_p.s._ the value **256** is chosen arbitrarily as representaiton for a realtively 'small' value in context of resolution. Different value may be used in implementation

**Comment by sananeminli** [comment]
Done on mobile.

**Comment by sananeminli** [comment]
Done also on the frontend.
