### ISSUE TITLE
Create custom issue labels.

### ISSUE THREAD

**Issue by yavuzsa** [SWE574-G3/Living-Stories-App#2]
GitHub's default issue labels do not fully cover our needs.
The goal is to create custom issue labels that can define the general characteristic of an issue.

We need issue labels that cover but not limited to the following items:
- [x] Create labels that denote the estimated effort.
- [x] Create labels that denote priority.

**Comment by JohnsL-U** [comment]
Added architecture label. Included a brief description for it.

**Comment by BurakKocak99** [comment]
- [ ] Add Domain specific labels

**Comment by BurakKocak99** [comment]
Added various labels:
Back-End
UI
Bug-Fix
Recommendation-Engine
UAT

**Comment by JohnsL-U** [comment]
Descriptions were added for all issue labels.

**Comment by yavuzsa** [comment]
- [ ] Add "unit test" label for quickly differentiate issues related to unit test coverage.
