### ISSUE TITLE
Create an Activty entity that stores activities of users.

### ISSUE THREAD

**Issue by yavuzsa** [SWE574-G3/Living-Stories-App#64]
We decided to have an Activity table in the databse which holds the activities done by each user.
The activity entity should contain _**userId, userName, userMedia, activityType, storyId, storyTitle, followindId, followingName**_ and _**timestamp**_ fileds.

**Comment by BurakKocak99** [comment]
thisi issue is resovled with comming [4bf19f3](https://github.com/SWE574-G3/Living-Stories-App/commit/4bf19f3c98c039c637e2d9695f52640500140036)
