### ISSUE TITLE
Identify places in code where actions we count as "Activity" is perofmed.

### ISSUE THREAD

**Issue by yavuzsa** [SWE574-G3/Living-Stories-App#65]
Since we decied to have an Activity table, we must write to this activity table in places where an activity is performed.
This issue covers identification of the places where an activity is performed according to our activity definition.
Things we consider as activity are: **_Likes, Comments, Stories, New User Follows_** by the followed users.

**Comment by yavuzsa** [comment]
Related to issue [#64](https://github.com/SWE574-G3/Living-Stories-App/issues/64) [Creation of Activity Entity]

**Comment by BurakKocak99** [comment]
For each action the following functions needs to be edited!

Post: StoryController/createStory function

Like: StoryController/likeStory function (check if it is "User liked story!")

Comment: CommentController/addCommentToStory function

Follow: UserController/followUser function
