### ISSUE TITLE
Record activities to the Activity table.

### ISSUE THREAD

**Issue by yavuzsa** [SWE574-G3/Living-Stories-App#66]
When an activity is performed, which is identified by an entry being inserted to the tables we consider as activity, another entry should be inserted into the Activity table with corresponding flag.
Things we consider as activity are: Likes, Comments, Stories, New User Follows by the followed users.

**Comment by BurakKocak99** [comment]
Related issues #68 #69 #70 #71  are created!

**Comment by BurakKocak99** [comment]
@yavuzsa  Please confirm that all of the activtiy record functionality works as expected and can be considered as done.

**Comment by yavuzsa** [comment]
Issue satisfied with commit [e8cb109](https://github.com/SWE574-G3/Living-Stories-App/commit/e8cb1096ef9b342dcd6464f452a701303322c6e7)
