### ISSUE TITLE
Write short descriptions for Main Tasks in the Wiki.

### ISSUE THREAD

**Issue by yavuzsa** [SWE574-G3/Living-Stories-App#8]
We have a Main Tasks page in our wiki. Available here: https://github.com/SWE574-G3/Living-Stories-App/wiki/Main-Tasks
In order to make each item's scope clear for everyone inside or outside the team, we need descriptions.

Currently we have a few examples ready. Rest should also be filled.

**Comment by JohnsL-U** [comment]
Updated with brief descriptions for each task.
