### ISSUE TITLE
Getting familiar with the base project.

### ISSUE THREAD

**Issue by yavuzsa** [SWE574-G3/Living-Stories-App#9]
Since we have decided to build on top of Sanan's app (Related Issue: https://github.com/SWE574-G3/Living-Stories-App/issues/5)
all the teams members should make themselves familiar with Sanan's app.
All team members should clone this repository and run it locally on their machines for testing and development purposes.

**Comment by Ali-Hakan** [comment]
I have published a remote branch I can work on. Done.

**Comment by JohnsL-U** [comment]
Base project was installed and deployed on every group member's local machine. Codes were added to the repository and studied.
